export default function Head() {
  return (
    <>
      <title>Frontend Mentor | Meet landing page</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0' />
      <link rel='icon' href='/favicon.png' />
    </>
  );
}
